version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./static:/app/static
      - ./static/uploads:/app/static/uploads
    ports:
      - "8889:8889"
    environment:
      - FLASK_ENV=development
      - FACEIT_API_KEY=${FACEIT_API_KEY}
