# Generated by Django 5.2.1 on 2025-08-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0002_match_competition_match_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
