# Generated by Django 5.2.1 on 2025-09-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0003_alter_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='seasons',
            field=models.ManyToManyField(blank=True, help_text='Seasons this player has participated in', related_name='players', to='cc.season'),
        ),
    ]
