# Generated by Django 5.2.1 on 2025-10-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0006_customevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmatch',
            name='extra_info',
            field=models.JSONField(blank=True, default=dict, help_text='Additional information about the event match (round name, bracket position, etc.)'),
        ),
    ]
