# Generated by Django 4.2.27 on 2026-10-07 15:37

from django.db import migrations, models


def set_elo_applied_db_default(apps, schema_editor):
    # Django 4.2 drops the DB-level default after AddField. Keep it so code
    # deployed before this migration (which doesn't know the column) can
    # still insert matches.
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE cc_match ALTER COLUMN elo_applied SET DEFAULT false"
        )


def drop_elo_applied_db_default(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE cc_match ALTER COLUMN elo_applied DROP DEFAULT"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0011_trophycase'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='elo_applied',
            field=models.BooleanField(default=False, help_text="Whether this match's result has been applied to team Elo"),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_elo_before',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_elo_change',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_elo_before',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_elo_change',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            set_elo_applied_db_default, drop_elo_applied_db_default
        ),
    ]
